# Generated by Django 4.2.5 on 2024-05-31 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_comment_name_alter_comment_uploadtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 17, 42, 31, 746924, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='listingDate',
            field=models.DateField(default=datetime.datetime(2024, 5, 31, 17, 42, 31, 745908, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='note',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
